# Use an official Nginx image as a base image
FROM nginx:alpine

# Copy your website files into the container
COPY neogym-html /usr/share/nginx/html

# Expose port 80 to access the website
EXPOSE 8081

# Run Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]

